version: "3.9"
services:
  mysql:
    image: mysql:latest
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=jpa
      - MYSQL_USER=jpa
      - MYSQL_PASSWORD=1234
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci